root: true
extends:
  - airbnb
env:
  browser: true
parser: babel-eslint
rules:
  no-mixed-operators:
    - off
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  react/no-array-index-key:
    - off
  import/prefer-default-export:
    - off
